language: java

jdk:
  #- openjdk7
  - openjdk8
  #- oraclejdk8
  - openjdk9
  #- oraclejdk9
  - openjdk10
  - openjdk11
  - oraclejdk11
  
script:
  - mvn -T 1C clean install
  - mvn -T 1C site
  - mvn -T 1C site:stage